'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class celular
    Public Property id_celular As Integer
    Public Property nombre As String
    Public Property caracteristicas As String
    Public Property modelo As String
    Public Property precio As Nullable(Of Decimal)
    Public Property stock As Nullable(Of Integer)

    Public Overridable Property detallepedido As ICollection(Of detallepedido) = New HashSet(Of detallepedido)

End Class
