'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ipv6_database_firewall_rules
    Public Property id As Integer
    Public Property name As String
    Public Property start_ipv6_address As String
    Public Property end_ipv6_address As String
    Public Property create_date As Date
    Public Property modify_date As Date

End Class
