'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pago
    Public Property id_pago As Integer
    Public Property confirmacionpago As String
    Public Property fechapago As Nullable(Of Date)
    Public Property id_pedido As Nullable(Of Integer)
    Public Property id_cliente As Nullable(Of Integer)

    Public Overridable Property cliente As cliente
    Public Overridable Property pedido As pedido

End Class
