'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pedido
    Public Property id_pedido As Integer
    Public Property fechapedido As Nullable(Of Date)
    Public Property id_detallepedido As Nullable(Of Integer)
    Public Property entregapedido As String

    Public Overridable Property detallepedido As detallepedido
    Public Overridable Property pago As ICollection(Of pago) = New HashSet(Of pago)

End Class
